site_name: Awesome Science
theme:
  name: material
  features:
  favicon: images/favicon.png
  logo: images/favicon.png
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/deverte/awesome-science
repo_name: Awesome Science
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Fc9u6yEzRH
edit_uri: ""
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg